### ISSUE TITLE
local files

### ISSUE THREAD

**Issue by g-braeunlich** [jasonwhite/rudolfs#11]
Can this also be used for serving (large) local files?
If not: what would be the estimated effort to implement this?
Depending on that: I would help to implement

**Comment by jasonwhite** [comment]
Sorry I didn't see this issue earlier. It should be pretty low effort to implement local file serving. All of the backend storage code is composable (see [`src/storage/`](https://github.com/jasonwhite/rudolfs/tree/master/src/storage)). There is already a disk storage backend, but it is currently only used for caching purposes. To implement local file storage, all you would need to do is expose the disk storage backend via the command line. The best way to do this is probably to change the command-line interface to use subcommands where each subcommand is a storage backend. For example:
```bash
rudolfs s3 --bucket <bucket>
rudolfs disk /data/lfs
rudolfs azure # (If Azure support is ever added.)
rudolfs gcs # (If Google Cloud Storage support is ever added.)
```

This would be a breaking change, but that's perfectly fine. It would be easy enough for existing users to migrate (`rudolfs [...]` -> `rudolfs s3 [...]`).

In theory, the only file that needs to change to support this is [`src/main.rs`](https://github.com/jasonwhite/rudolfs/blob/master/src/main.rs).

**Comment by g-braeunlich** [comment]
Hey Jason
Thanks for your reply.
In my opinion, the first step would be to upgrade to hyper 0.13, which supports the new async / await functionality.
As the above suggestion would involve some sort of polymorphism at the stage of loading a backend and your backends are created as futures, this would solve a lot of trouble.
What do you think?

**Comment by jasonwhite** [comment]
Indeed, it would be good to upgrade to the new async/await, but it's not a mandatory first step as we can just `Box` it up or create an enum containing the possibilities. Although, I would be happy to take an async/await pull request as well. ;-)

**Comment by g-braeunlich** [comment]
I also do not have much time currently. But lets see. Would be a cool project

**Comment by jasonwhite** [comment]
> it would be good to upgrade to the new async/await, but it's not a mandatory first step

Everything has been converted to async/await, so implementing this issue should be pretty easy now if anyone is interested in taking a stab at it.

**Comment by greyltc** [comment]
@jasonwhite thank you and thank Esri for a really great project! I found it earlier today and after playing around with it a bit, it looks like the best LFS server implementation out there. I've packaged it in the Arch User Repository: https://aur.archlinux.org/packages/rudolfs/

I don't know rust, but I've been wanting to get to know it for a while now, so I'll see if I can learn some rust while trying my hand at adding this feature.

Also, I think the optional encryption stuff you've done in https://github.com/jasonwhite/rudolfs/commit/b52a30921b60c604fe9f043c61b71245352c3551 makes a lot of sense with local storage.

**Comment by jasonwhite** [comment]
@greyltc Thanks for creating the AUR package! I'll put a link to that on the readme.

PRs are very much welcome. As I mentioned earlier, I think the first step is to do some refactoring such that each backend becomes its own subcommand. If you start working on this, drop us a note here. Otherwise, I'll get around to it eventually.

**Comment by jasonwhite** [comment]
Actually, I went ahead and started on this. Should have a PR up soon.

**Comment by greyltc** [comment]
I'll test this out on my setup soon! Will you cut a new release for this?

BTW, in the mean time, in order to get local storage working, I ran a local S3 server: https://github.com/minio/minio
works pretty well! but it will be great to chuck out that whole layer!

**Comment by jasonwhite** [comment]
> Will you cut a new release for this?
 
v0.3 is out now 👍

**Comment by suy** [comment]
Awesome, thank you very much! I know reactions exist to avoid "thank you" comments and the like, but I wanted to leave something more personal. I'm quite excited by this. 😍
