### ISSUE TITLE
Failed to query S3 bucket... couldn't find AWS credentials

### ISSUE THREAD

**Issue by paulkaefer** [jasonwhite/rudolfs#15]
Similar to #13, I'm getting the following:
```
 2020-03-09T16:17:16.005 ERROR rudolfs::storage::s3 > Failed to query S3 bucket ('Couldn't find AWS credentials in environment, credentials file, or IAM role.'). Retrying...
```

I have credentials in `~/.aws/credentials`, and can connect to S3 using the aws cli. The shell script I'm using to run the rudolfs Docker container contains `export`s with my credentials as well. So this error message surprises me.

I don't have Rust experience, and not much with Docker, but if you could just point me in the right direction to debug, I'd be grateful!

**Comment by jasonwhite** [comment]
Is the file `~/.aws/credentials` inside or outside the Docker container? If outside, there is no way Docker can know about it. Docker will also only use environment variables from the host system if they are specified with the `-e` flag with `docker run`.

The easiest way to get your credentials passed into the Docker container is to use the `docker-compose.yml` file provided in the root of the repository. See https://github.com/jasonwhite/rudolfs#production for instructions on setting that up.

**Comment by paulkaefer** [comment]
@jasonwhite that's helpful, but I do have the variables set in `.env` file. Won't docker read from this?

**Comment by jasonwhite** [comment]
I think only docker-compose will read `.env` files automatically.

**Comment by paulkaefer** [comment]
@jasonwhite thanks. I'm exploring [DVC](https://dvc.org/doc/get-started/agenda) now, as I think it meets some additional needs. But this has been a very helpful thread!
