### ISSUE TITLE
kill process that runs on startup?

### ISSUE THREAD

**Issue by paulkaefer** [jasonwhite/rudolfs#19]
via `htop`, I see this, which I suspect is from tinkering with rudolfs a few months ago:
![Screen Shot 2020-09-15 at 09 19 21](https://user-images.githubusercontent.com/2408155/93222430-90ec8080-f734-11ea-91ff-44abc992a5d3.png)

I can run `ps -e | grep -i "rudo"` and `sudo kill -9 xxxxx` that process, but it keeps coming back.

Is there somewhere I can remove this from a scheduler of some sort? I just don't need it to be running all the time!

**Comment by jasonwhite** [comment]
Are you sure you're killing the process and not individual threads? If it is the latter, then I'd expect a new thread to be spawned to maintain N threads in the pool. If you're sure you are killing the process, then there could be a Docker container with `--restart=always` specified. There isn't a way for `Rudolfs` to restart its own process if it is killed. That is something normally handled by Docker or systemd.

**Comment by paulkaefer** [comment]
Thanks, @jasonwhite. You're right. `docker stats` showed the container name, and `docker stop`/`docker rm` were what I was looking for.
