### ISSUE TITLE
X-Forwarded-Host header support

### ISSUE THREAD

**Issue by subvillion** [jasonwhite/rudolfs#31]
Please add X-Forwarded-* headers support or some ENV option to set Host by hands, now as I see used simple Host header: 

```api: req.base_uri().path_and_query("/api").build().unwrap()```

this broke almost all under balancer usage, and unusable  in k8s

**Comment by jasonwhite** [comment]
I'm happy to take any pull requests. I don't have too much time to work on this these days.

It should be a matter of updating this function to use `X-Forwarded-Host` (if present): https://github.com/jasonwhite/rudolfs/blob/4d86a498d39ae9fa0647cf0d22b6bce9f15d1892/src/hyperext.rs#L56-L63

**Comment by jasonwhite** [comment]
This should be fixed on master. I'll publish a new release after accumulating a few more changes.
