### ISSUE TITLE
What are the minimal permissions that are required for the server to run on an AWS bucket?

### ISSUE THREAD

**Issue by LiorZ** [jasonwhite/rudolfs#45]
I created a user on AWS IAM management console exclusively for the server. However, after setting a minimal set of permissions (READ/WRITE/LIST/etc) which I thought were necessary, the server returned an error upon launch:
`Invalid S3 credentials`

After allowing all S3 operations on the LFS bucket, the server runs smoothly.

What is the minimal set of permissions required for the server to interact properly with the S3 service?

**Comment by jasonwhite** [comment]
These are the only actions that Rudolfs needs to be able to perform:
 - `s3:ListBucket` for doing the `HEAD` request on the bucket to do an early check on credentials during startup. This isn't technically necessary, but it catches invalid credentials early on.
 - `s3:GetObject` for downloading LFS objects and checking the size.
 - `s3:PutObject` for uploading LFS objects.
 
Objects are never deleted from S3, so `s3:DeleteObject` can be denied.

See https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html#amazons3-actions-as-permissions for how these map to permissions.

As far as I understand, Rudolfs just needs Read/Write on objects and List for buckets.
