### ISSUE TITLE
Uploading lfs objects ... actively refused

### ISSUE THREAD

**Issue by GertyP** [jasonwhite/rudolfs#48]
I've been documenting steps for setting up a personal git multi-repository server on a simple home LAN linux box, complete with a rudolfs server.  Although I've found a few important details and steps to be missing from the rudolfs documentation, I've got to the point where I believe everything should be set up and running correctly, however when making use of LFS tracked objects, the initial push from a test PC -
```
git push --set-upstream gitolite3@myserver:somespace/somenewrepo master
```
fails uploading the LFS data with -
```
Remote "gitolite3@myserver:somespace/somenewrepo" does not support the Git LFS locking API. Consider disabling it with:
  $ git config lfs.http://myserver:8015/somespace/somenewrepo.locksverify false
Uploading LFS objects:   0% (0/7), 0 B | 0 B/s, done.
batch response: Post "http://myserver:8015/somespace/somenewrepo/objects/batch": dial tcp 192.168.1.71:8015: connectex: No connection could be made because the target machine actively refused it.
error: failed to push some refs to 'myserver:somespace/somenewrepo'
```

Firstly, sorry in advance in the highly likely situation that the problem is nothing to do with rudolfs, but documenting this particular issue might at least leave a tip for anyone else running in to the same issue.  I wondered if anyone has suggestions about what I might have missed or done wrong.

Here are a few things I've checked -

I've no problems doing normal, non-LFS git operations with this 'myserver';  I can clone, edit, and push repo changes from my test PC to this git repo server.

With a new repo on my test PC that uses LFS-tracked files, it has a '.lfsconfig' file with -
```
[lfs]
	url = "http://myserver:8015/somespace/somenewrepo"
```
It's not clear to me whether this URL format is suitable for the rudolfs server. I could see no rudolfs documentation on if or how the server handles those '/' path separators in the URL.  Should this be fine or does anything need configuring on the rudolfs server to know how those separators should be handled?

On the linux Git + LFS server, I set up a systemd service to run '/etc/systemd/system/rudolfs.service' -
```
[Unit]
Description=Rudolfs (Git LFS) server
After=network.target

[Service]
Type=simple
User=rudolfs_user
Group=devservices_group
Environment="RUDOLFS_KEY=xxxxxxxxxx...."
ExecStart=/usr/local/bin/rudolfs --cache-dir /rudolfs/cache --host localhost:8015 --max-cache-size=2GiB local --path=/rudolfs/storage

[Install]
WantedBy=multi-user.target
```

and I can see this service is running and listening on :8015 -

```
systemctl status rudolfs.service

rudolfs.service - Rudolfs (Git LFS) server
	 Loaded: loaded (/etc/systemd/system/rudolfs.service; enabled; vendor preset: enabled)
	 Active: active (running) since Sun 2022-09-25 19:26:45 BST; 16h ago
   Main PID: 474 (rudolfs)
	  Tasks: 5 (limit: 4224)
		CPU: 111ms
	 CGroup: /system.slice/rudolfs.service
			 └─474 /usr/local/bin/rudolfs --cache-dir /rudolfs/cache --host localhost:8015 --max-cache-size=2GiB local --path=/rudolfs/storage

... systemd[1]: Started Rudolfs (Git LFS) server.
... INFO  rudolfs > Initializing storage...
... rudolfs > Local disk storage initialized.
... rudolfs > Listening on [::1]:8015
```

On my test PC (on the same 192.168.1.??? sub-net), I use a powershell port check to see that the server is only partially connecting on port 8015 -
```
> Test-NetConnection -ComputerName myserver -Port 8015
	WARNING: TCP connect to (192.168.1.71 : 8015) failed
	ComputerName           : myserver
	RemoteAddress          : 192.168.1.71
	RemotePort             : 8015
	InterfaceAlias         : Ethernet
	SourceAddress          : 192.168.1.32
	PingSucceeded          : True
	PingReplyDetails (RTT) : 1 ms
	TcpTestSucceeded       : False
```
The port ping success at least tells me that I am initially reaching myserver:8015 but something thereafter is failing, which would seem to coincide with the original "...target machine actively refused it" error.

Finally, the 'myserver' machine has its 'iptables' configured as follows -
```
#Trivially allow localhost (lo) connections -
sudo iptables -A INPUT -i lo -j ACCEPT

#Allow 192.168.1.[2..255] IPs to connect to the rudoLFS server, listening at port 8015, otherwise block all other connections to 8015 -
sudo iptables -A INPUT -p tcp --dport 8015 -m iprange --src-range 192.168.1.2-192.168.1.255 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 8015 -j DROP
```
And these rules are preserved across reboots through the use of the 'iptables-persistent' utility/service.
**Update**:  I've also tested removing all these iptables rules (sudo iptables -F INPUT), leaving no entries remaining, and I get the same behaviour.

Is there something I can try to better home in on the the problem or does anyone have suggestions as to the source of the problem?
Also, once I have this issue resolved, would it be useful to anyone if I were to document my full, detailed, multi-repo. git and LFS server configuration set-up steps (perhaps in the 'discussions' section) in case it's helpful for others, like me, who might like slightly more explicit and detailed steps for using 'rudolfs'?

**Comment by jasonwhite** [comment]
I believe your `.lfsconfig` file should be:
```
[lfs]
url = "http://myserver:8015/api/somespace/somenewrepo"
```
(Note the `api` in the path.)

However, I think the error is happening before Rudolfs even gets the request because I would expect a different error message with such a configuration mistake.

This looks like a firewall configuration problem to me. I'm no iptables expert, so I can't tell if your iptables config is correct. Your router could also have a firewall and be blocking port 8015.

**Comment by jasonwhite** [comment]
I also noticed that the server is starting up on `[::1]:8015` and `[::1]` is the IPv6 loopback interface, which means it is a network interface private to the machine itself. See also https://github.com/jasonwhite/rudolfs/issues/38#issuecomment-973721511.

I believe the fix should be to specify `--port 8015` instead of `--host localhost:8015`. The former will use the IP `0.0.0.0`, which means "bind this server to *all* available network interfaces, both internal and external".

**Comment by GertyP** [comment]
Thanks very much Jason.
That has fixed the issue.

Even though the readme/docs show the use of '/api/' in the .lfsconfig url, it wasn't clear to me whether that's just an example of the kind of space grouping that we appear to be able to use for multiple repository git servers (e.g. 'git clone gitolite3@myserver:abc/def/somereponame') or whether it's a critical, separate part of the LFS url ... which I now see it is.  So this 'abc/def/somereponame' example would then best be configured to have a LFS URL of 'http://myserver:8015**/api**/abc/def/somereponame'.

Thanks again.

**Comment by jasonwhite** [comment]
Thanks for the feedback. I updated the docs in https://github.com/jasonwhite/rudolfs/commit/9f2eaadc108b8d69185dc560c371a9d9f0115fc2 to help clarify that a bit.
