### ISSUE TITLE
Uploading LFS objects hangs

### ISSUE THREAD

**Issue by tcamin** [jasonwhite/rudolfs#50]
I'm testing rudolfs on my local machine but I'm having an issue where uploading lots of lfs systematically hangs.

I built the master binary and launched it with a local storage `./rudolfs --host=0.0.0.0:8080 local --path=/tmp/lfs-storage`. From an existing repo with approximately 5k lfs objects I'm force pushing all lfs with `git lfs push origin --all`.

I see rudolfs logging POST (verify) and PUT (objects) for every object upload, and see objects being added to /tmp/lfs-storage/objects. So far so good, however at one point I no longer see the puts but instead just a bunch of

```
POST /api/Org/Repo/objects/batch - 200 OK
```

The client remaining stuck at 

```
Uploading LFS objects:  65% (4244/6521), 959 MB | 105 MB/s
```

If I cancel and relaunch the `git lfs push origin --all`

I just see a number of

```
POST /api/Org/Repo/objects/batch - 200 OK
```

with the client remaining stuck as mentioned above

What would be the right way to debug this?

**Comment by jasonwhite** [comment]
I'll try to reproduce later today/tomorrow.

One idea springs to mind: If `/tmp` is backed by RAM, then maybe your system could be running out of RAM and using swap space, which could slow things down significantly.

**Comment by tcamin** [comment]
Thanks! On my machine `/tmp` is not in RAM.

**Comment by tcamin** [comment]
Closing. git lfs (client) seems to be stuck since I'm missing (both locally and remotely) some objects that are in the lfs index. It's unclear why it remains stuck, but it's probably an unsupported scenario.
