### ISSUE TITLE
Could the encryption be made optional? 

### ISSUE THREAD

**Issue by ranrub** [jasonwhite/rudolfs#7]
I would like my files to be accessible on the s3 repo for distribution via e.g. cloudfront.

**Comment by flomlo** [comment]
Hi!

I would be interested in making encryption optiona as welll, though my main use case is the local storage backend. There are filesystems with built-in compression and that would be a neat way to make use of it. In my case it would reduce the bloat by a factor of ~3.
Furthermore, I do like the increased transparency.

I had a look at the branch created 2019, which introduced the option, but never made it into main.

Would you consider accepting a PR with the code from 2019 adapted to the current version? I can test it with the local backend, but I don't have any means to test it on S3.

**Comment by jasonwhite** [comment]
> Would you consider accepting a PR with the code from 2019 adapted to the current version? I can test it with the local backend, but I don't have any means to test it on S3.

Yes, I'm always open to PRs! Adapting that old PR to recent changes should be relatively straightforward. The main thing is that the `impl Storage for Either` should no longer be necessary because `Box` is now used to abstract away the composition of backends.

When you have a PR, I can test it on S3. (I have a free-tier account that I test with.)

**Comment by greyltc** [comment]
I'm working on implementing this here: https://github.com/greyltc/rudolfs/tree/encryption-optional based on what you've already done in https://github.com/jasonwhite/rudolfs/pull/8 Jason.
Bear with me here please, this is my first time rusting. At present, what I've got there in https://github.com/greyltc/rudolfs/commit/5c0ea444af10389b56a023066a257f88c57f32cd completely diables encryption in a non-optional way. I've played around with it a bit, and this seems to work fine. Now I'll see about adding back in the option to turn encryption on (I'm not sure I understand why so much `Either` code needs to exist for this in the original PR).

**Comment by jasonwhite** [comment]
@greyltc I went ahead and revived my old PR: #67. Includes tests and everything. Let me know if this works for you.

**Comment by greyltc** [comment]
@jasonwhite tested. working like a charm! thanks very much!

**Comment by greyltc** [comment]
@jasonwhite could we get a 0.3.7 tag for this?

**Comment by jasonwhite** [comment]
@greyltc Done.
