### ISSUE TITLE
2.9.0 Results in Bad Request

### ISSUE THREAD

**Issue by markkohlmann** [jasonwhite/rudolfs#9]
2.9.0 of GIT LFS does not seem to work with Rudolfs.  A "Bad Request" is returned.  Only discrepancy I can find is the addition of a transfers object to the json: '"transfers":["lfs-standalone-file","basic"]'.  Rolling back 2.7.1 seems to work fine.  Running GIT on Windows as the client end.  Server is on Ubuntu 18.04LTS running in a docker-compose container.

**Comment by jasonwhite** [comment]
As a temporary workaround with Git LFS 2.9, does setting `lfs.basictransfersonly=true` work?

    git config lfs.basictransfersonly true

**Comment by tomgigler** [comment]
Your suggested workaround worked for me.  Any plans to fix this going forward?

**Comment by jasonwhite** [comment]
v0.2.7 should fix this issue.
